---
- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - lua5.3
    - liblua5.3-dev
    - rsync
    - cmake
    - g++
  become: true
  when: lsyncd_install_dependencies
