---
- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - lua5.2
    - liblua5.2-dev
    - rsync
    - cmake
    - g++
  become: true
  when: lsyncd_install_dependencies
